application: wherecaniswim
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/images
  static_dir: static/images

- url: /about
  static_files: static/templates/about.html
  upload: static/templates/about.html

  
- url: /favicon.ico
  static_files: /images/favicon.ico
  upload: /images/favicon.ico
  
- url: /update-sessions
  script: updateSessions.application

- url: /.*
  script: WhereCanISwim.application
